# -*- coding: utf-8 -*-
"""SCRAPING - MC361D5X2092.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6Up4JWjicFHtVU1ojy-dCaVVIEf5FYl
"""

!pip install google-play-scraper

from google_play_scraper import reviews_all, reviews, Sort
import pandas as pd

scrapreview = reviews(
    'com.tokopedia.tkpd',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count = 30000,
    filter_score_with=5
)

data = pd.DataFrame(scrapreview[0])
data.to_csv('ULASAN_TOKOPEDIA.csv', index=False)